# Generated by Django 6.0.3 on 2026-04-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, unique=True, verbose_name='Страна (именительный падеж)')),
                ('country_genitive', models.CharField(help_text="Как в вопросе: 'Столица [чего]?'", max_length=100, verbose_name='Страна (родительный падеж)')),
                ('capital', models.CharField(max_length=100, verbose_name='Столица')),
            ],
        ),
    ]
